### ISSUE TITLE
Change License to MIT

### ISSUE THREAD

**Issue by YegorZaremba** [navendu-pottekkat/nsfw-filter#44]
I have no idea what's the difference between these licences, but most github repos use `MIT License`
Do we have any reasons to use `GPL-3.0 License`?

**Comment by navendu-pottekkat** [comment]
@YegorZaremba I used GPL because if this code is used by somebody, then they have to make it open-source. 

I did not want anyone to "privatize" it.

GPL requires if a distributed software uses this code, then it has to be made open-source.

MIT software does not have any such restrictions. 

Is there a reason why you wanted to change the License? 🤔

**Comment by navendu-pottekkat** [comment]
https://stackoverflow.com/questions/3902754/mit-vs-gpl-license

**Comment by YegorZaremba** [comment]
Okey, just would like to know why we use this one

> Is there a reason why you wanted to change the License? :thinking:

lmao, no actually

**Comment by navendu-pottekkat** [comment]
> Okey, just would like to know why we use this one
> 
> > Is there a reason why you wanted to change the License? thinking
> 
> lmao, no actually

I usually use MIT license idk why I went with GPL. But it works out!
